services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my-network

  app:
    build:
      context: .
    container_name: app
    environment:
      - "MY_DB_CONNECTION_STRING=Host=postgres;Port=5432;Database=my_db;Username=postgres;Password=1234"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - my-network
    volumes:
      - ./appsettings.json:/app/appsettings.json

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
