version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    image: suppyour/backend:latest
    container_name: app
    environment:
      MY_DB_CONNECTION_STRING: "User ID=postgres;Password=1234;Host=postgres;Port=5432;Database=my_db"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
